from fastapi import APIRouter, Depends, Query

from src.api.deps import DbSession
from src.api.schemas.search import TechRadarResponse, TrendingPaperResponse, TrendingRepoResponse
from src.storage.repositories.metrics_repo import MetricsRepository

router = APIRouter(prefix="/trending", tags=["Trending"])


@router.get("/papers", response_model=list[TrendingPaperResponse])
async def get_trending_papers(
    db: DbSession,
    period: str = Query("week"),
    category: str | None = None,
    limit: int = Query(20, ge=1, le=100),
):
    metrics = MetricsRepository(db)
    trending = await metrics.get_trending(
        entity_type="paper", category=category, limit=limit
    )

    return [
        TrendingPaperResponse(
            id=str(t.entity_id),
            title="",
            trending_score=t.total_score,
            category=t.category,
        )
        for t in trending
    ]


@router.get("/repos", response_model=list[TrendingRepoResponse])
async def get_trending_repos(
    db: DbSession,
    period: str = Query("week"),
    language: str | None = None,
    topic: str | None = None,
    limit: int = Query(20, ge=1, le=100),
):
    metrics = MetricsRepository(db)
    trending = await metrics.get_trending(
        entity_type="repository", category=topic, limit=limit
    )

    return [
        TrendingRepoResponse(
            id=str(t.entity_id),
            full_name="",
            trending_score=t.total_score,
        )
        for t in trending
    ]


@router.get("/tech-radar", response_model=TechRadarResponse)
async def get_tech_radar(
    period: str = Query("month"),
):
    # Tech radar is generated by the weekly report job
    return TechRadarResponse(adopt=[], trial=[], assess=[], hold=[])
