"""initial

Revision ID: 452061ad82dc
Revises: 
Create Date: 2026-02-06 11:32:26.523299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452061ad82dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_channels', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_type', 'alerts', ['alert_type'], unique=False)
    op.create_table('api_rate_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('requests_remaining', sa.Integer(), nullable=True),
    sa.Column('requests_limit', sa.Integer(), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name')
    )
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_jobs_source', 'crawl_jobs', ['source', 'status'], unique=False)
    op.create_table('metrics_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('velocity_1d', sa.Float(), nullable=True),
    sa.Column('velocity_7d', sa.Float(), nullable=True),
    sa.Column('velocity_30d', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'recorded_at', name='uq_metrics_entity_date')
    )
    op.create_index('idx_metrics_date', 'metrics_history', ['recorded_at'], unique=False)
    op.create_index('idx_metrics_entity', 'metrics_history', ['entity_type', 'entity_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=20), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('semantic_scholar_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_normalized', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('influential_citation_count', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_vietnamese', sa.Boolean(), nullable=False),
    sa.Column('vietnam_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index('idx_papers_categories', 'papers', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_papers_published_date', 'papers', ['published_date'], unique=False, postgresql_using='btree')
    op.create_index('idx_papers_topics', 'papers', ['topics'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('readme_summary', sa.Text(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=False),
    sa.Column('clone_url', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frameworks', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('watchers_count', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.Column('last_release_at', sa.DateTime(), nullable=True),
    sa.Column('last_release_tag', sa.String(length=50), nullable=True),
    sa.Column('commit_count_30d', sa.Integer(), nullable=False),
    sa.Column('has_readme', sa.Boolean(), nullable=False),
    sa.Column('has_license', sa.Boolean(), nullable=False),
    sa.Column('has_tests', sa.Boolean(), nullable=False),
    sa.Column('has_docker', sa.Boolean(), nullable=False),
    sa.Column('has_ci', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('repo_created_at', sa.DateTime(), nullable=True),
    sa.Column('repo_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index('idx_repos_frameworks', 'repositories', ['frameworks'], unique=False, postgresql_using='gin')
    op.create_index('idx_repos_language', 'repositories', ['primary_language'], unique=False)
    op.create_index('idx_repos_stars', 'repositories', ['stars_count'], unique=False, postgresql_using='btree')
    op.create_index('idx_repos_topics', 'repositories', ['topics'], unique=False, postgresql_using='gin')
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.String(length=200), nullable=False),
    sa.Column('subscriber_type', sa.String(length=50), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=500), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'subscription_type', 'target_value', name='uq_subscription')
    )
    op.create_table('trending_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('community_score', sa.Float(), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rank_in_category', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'period_start', name='uq_trending_entity_period')
    )
    op.create_index('idx_trending_category', 'trending_scores', ['category', 'rank_in_category'], unique=False)
    op.create_index('idx_trending_score', 'trending_scores', ['total_score'], unique=False)
    op.create_table('paper_repo_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_via', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'repo_id', name='uq_paper_repo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_repo_links')
    op.drop_index('idx_trending_score', table_name='trending_scores')
    op.drop_index('idx_trending_category', table_name='trending_scores')
    op.drop_table('trending_scores')
    op.drop_table('subscriptions')
    op.drop_index('idx_repos_topics', table_name='repositories', postgresql_using='gin')
    op.drop_index('idx_repos_stars', table_name='repositories', postgresql_using='btree')
    op.drop_index('idx_repos_language', table_name='repositories')
    op.drop_index('idx_repos_frameworks', table_name='repositories', postgresql_using='gin')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_index('idx_papers_topics', table_name='papers', postgresql_using='gin')
    op.drop_index('idx_papers_published_date', table_name='papers', postgresql_using='btree')
    op.drop_index('idx_papers_categories', table_name='papers', postgresql_using='gin')
    op.drop_table('papers')
    op.drop_index('idx_metrics_entity', table_name='metrics_history')
    op.drop_index('idx_metrics_date', table_name='metrics_history')
    op.drop_table('metrics_history')
    op.drop_index('idx_crawl_jobs_source', table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_table('api_rate_limits')
    op.drop_index('idx_alerts_type', table_name='alerts')
    op.drop_index('idx_alerts_created', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
