"""add hf_models and hf_papers tables

Revision ID: b35dadd51d6a
Revises: f7a8b9c0d1e2
Create Date: 2026-02-10 03:08:38.279379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b35dadd51d6a'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hf_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('pipeline_tag', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=200), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('library_name', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=200)), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('parameter_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at_hf', sa.DateTime(), nullable=True),
    sa.Column('last_modified_hf', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hf_models_downloads', 'hf_models', ['downloads'], unique=False, postgresql_using='btree')
    op.create_index('idx_hf_models_likes', 'hf_models', ['likes'], unique=False, postgresql_using='btree')
    op.create_index('idx_hf_models_pipeline_tag', 'hf_models', ['pipeline_tag'], unique=False)
    op.create_index('idx_hf_models_tags', 'hf_models', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_hf_models_model_id'), 'hf_models', ['model_id'], unique=True)
    op.create_table('hf_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hf_papers')
    op.drop_index(op.f('ix_hf_models_model_id'), table_name='hf_models')
    op.drop_index('idx_hf_models_tags', table_name='hf_models', postgresql_using='gin')
    op.drop_index('idx_hf_models_pipeline_tag', table_name='hf_models')
    op.drop_index('idx_hf_models_likes', table_name='hf_models', postgresql_using='btree')
    op.drop_index('idx_hf_models_downloads', table_name='hf_models', postgresql_using='btree')
    op.drop_table('hf_models')
    # ### end Alembic commands ###
